/* WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM A .SM FILE.
 * Changes made here will certainly be overwritten.
 */

/* 
 * (C) 2003 Clemson University and The University of Chicago 
 *
 * See COPYING in top-level directory.
 */

#include <string.h>
#include <assert.h>

#include "pvfs2-debug.h"
#include "job.h"
#include "gossip.h"
#include "str-utils.h"
#include "state-machine.h"



static PINT_sm_action void_action(
	struct PINT_smcb *smcb, job_status_s *js_p);

static struct PINT_state_s ST_void_action_state;
static struct PINT_pjmp_tbl_s ST_void_action_state_pjtbl[];
static struct PINT_tran_tbl_s ST_void_action_state_trtbl[];

struct PINT_state_machine_s pvfs2_void_sm = {
	.name = "pvfs2_void_sm",
	.first_state = &ST_void_action_state
};

static struct PINT_state_s ST_void_action_state = {
	 .state_name = "void_action_state" ,
	 .parent_machine = &pvfs2_void_sm ,
	 .flag = SM_RUN ,
	 .action.func = void_action ,
	 .pjtbl = NULL ,
	 .trtbl = ST_void_action_state_trtbl 
};

static struct PINT_tran_tbl_s ST_void_action_state_trtbl[] = {
	{ .return_value = -1 ,

	 .flag = SM_TERM }
};

#ifndef WIN32
# 27 "src/common/misc/void.sm"
#endif


static PINT_sm_action void_action(
        struct PINT_smcb *smcb, job_status_s *js_p)
{
    gossip_err("This pvfs2_void state machine should never run!\n");
    PINT_smcb_set_complete(smcb);
    return SM_ACTION_COMPLETE;
}

/*
 * Local variables:
 *  mode: c
 *  c-indent-level: 4
 *  c-basic-offset: 4
 * End:
 *
 * vim: ft=c ts=8 sts=4 sw=4 expandtab
 */
